/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Main.TheBostonInsuranceModel;
import Model.Account.Account;
import Model.Customer.Payment.PaymentCard;
import Model.Customer.Policy.CustomerPolicy;
import Model.Customer.Policy.CustomerPolicyDirectory;
import Model.Customer.Quote.CustomerQuote;
import Model.Customer.Quote.CustomerQuoteDirectory;
import Model.Thirdparty.PAYMENT.PaymentCardDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prane
 */
public class BillingPage extends javax.swing.JPanel {

    /**
     * Creates new form BillingPage
     */
    private TheBostonInsuranceModel BIM;
    private JPanel workPanel;
    private CustomerQuote custQuote;
    private PaymentCardDirectory paymentCardDirectory;
    private PaymentCard paymentCard;
    private CustomerPolicyDirectory customerPolicyDirectory;
    private CustomerQuoteDirectory customerQuoteDirectory;
    private Account account;
    
    public BillingPage(TheBostonInsuranceModel BIM, JPanel workPanel, CustomerQuote custQuote, Account account) {
        initComponents();
        this.BIM = BIM;
        this.workPanel = workPanel;
        this.custQuote = custQuote;
        this.account = account;
        btnPayment.setEnabled(false);
        paymentCardDirectory = BIM.getPaymentCardDirectory();
        paymentCard = new PaymentCard();
        customerPolicyDirectory = BIM.getCustomerPolicyDirectory();
        customerQuoteDirectory = BIM.getCustomerQuoteDirectory();

        txtTotal.setText(String.valueOf(custQuote.getQuote().getPremiumAmount()));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCardName = new javax.swing.JLabel();
        txtCardName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        lblCardNumber = new javax.swing.JLabel();
        lblStreetAdd = new javax.swing.JLabel();
        txtStreetAdd = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        btnCreateAcc1 = new javax.swing.JButton();
        lblExpMonth = new javax.swing.JLabel();
        lblExpYear = new javax.swing.JLabel();
        lblCVV = new javax.swing.JLabel();
        txtExpMonth = new javax.swing.JTextField();
        txtExpYear = new javax.swing.JTextField();
        txtCVV = new javax.swing.JTextField();
        btnCheckCard = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        lblCardName1 = new javax.swing.JLabel();

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/topLogo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("                                                                                             Billing Page");

        jLabel10.setForeground(new java.awt.Color(153, 0, 51));
        jLabel10.setText("Card Details");

        lblCardName.setText("Card Name");

        txtCardName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNameActionPerformed(evt);
            }
        });

        txtCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNumberActionPerformed(evt);
            }
        });

        lblCardNumber.setText("Card Number");

        lblStreetAdd.setText("Street Address");

        txtStreetAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddActionPerformed(evt);
            }
        });

        lblCity.setText("City");

        lblState.setText("State");

        lblZip.setText("Zip Code");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(204, 204, 204));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(153, 0, 0));
        btnPayment.setText("Make a payment");
        btnPayment.setEnabled(false);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnCreateAcc1.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateAcc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateAcc1.setForeground(new java.awt.Color(153, 0, 0));
        btnCreateAcc1.setText("< back");
        btnCreateAcc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAcc1ActionPerformed(evt);
            }
        });

        lblExpMonth.setText("Expiration Month");

        lblExpYear.setText("Expiration Year");

        lblCVV.setText("CVV");

        btnCheckCard.setBackground(new java.awt.Color(204, 204, 204));
        btnCheckCard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCheckCard.setForeground(new java.awt.Color(153, 0, 0));
        btnCheckCard.setText("Verify Details");
        btnCheckCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckCardActionPerformed(evt);
            }
        });

        lblCardName1.setText("Total Amount");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(btnCheckCard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblStreetAdd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreetAdd)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 334, Short.MAX_VALUE)
                                        .addComponent(btnPayment)
                                        .addGap(250, 250, 250))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtCity)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(lblExpMonth)
                                                .addGap(70, 70, 70)
                                                .addComponent(lblExpYear))
                                            .addComponent(lblCity))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblState)
                                                .addGap(201, 201, 201))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(lblCVV)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblZip)
                                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnCreateAcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblCardName1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLName)))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblCardNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtExpMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtExpYear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCVV)))
                        .addGap(93, 93, 93))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAcc1)
                .addGap(3, 3, 3)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCardName1))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblLName)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCardName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNumber)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCVV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExpMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStreetAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(lblState)
                            .addComponent(lblZip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(btnCheckCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPayment))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblExpMonth)
                        .addComponent(lblExpYear)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCardNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardNameActionPerformed

    private void txtCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardNumberActionPerformed

    private void txtStreetAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        custQuote.getQuote().setPaymentCard(paymentCard);
        custQuote.getQuote().setPaymentStatus("completed");

        CustomerPolicy custPolicy = customerPolicyDirectory.createCustomerPolicy(custQuote.getCustomerAccount(), "issued", custQuote.getQuote().getPremiumAmount(), custQuote.getQuote().getVehicles());
        custPolicy.getPolicy().setQuote(custQuote.getQuote());

        String packageType = custQuote.getQuote().getPackageType();
        custPolicy.getPolicy().setPackageType(packageType);

        if (packageType.equals("standard")) {
            custPolicy.getPolicy().setStandardPackage(custQuote.getQuote().getStandardPackage());
        } else {
            custPolicy.getPolicy().setPremiumPackage(custQuote.getQuote().getPremiumPackage());
        }

        customerQuoteDirectory.deleteCustomerQuote(custQuote);

        CardLayout layout = (CardLayout) workPanel.getLayout();
        UI.Comp.Agent.PolicySuccessPage policySuccessPage = new UI.Comp.Agent.PolicySuccessPage(BIM, workPanel, custPolicy, account);
        workPanel.add("PolicySuccessPage", policySuccessPage);
        layout.next(workPanel);        

    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnCreateAcc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAcc1ActionPerformed
        // TODO add your handling code here:
        workPanel.remove(this);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.previous(workPanel);        

    }//GEN-LAST:event_btnCreateAcc1ActionPerformed

    private void btnCheckCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckCardActionPerformed
        // TODO add your handling code here:
        String CardName = txtCardName.getText();
        String CardNumberText = txtCardNumber.getText();
        String Cvv = txtCVV.getText();
        String StreetAdd = txtStreetAdd.getText();
        String City = txtCity.getText();
        String State = txtState.getText();
        String Zip = txtZip.getText();

        // Validate Card Number
        long CardNumber = 0;
        try {
            CardNumber = Long.parseLong(CardNumberText);
            if (CardNumber <= 0 || String.valueOf(CardNumber).length() != 16) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Card Number. Please enter a valid 16-digit positive integer.");
            return; // Stop further processing if Card Number is invalid
        }

        // Validate Expiration Month
        int ExpMonth = 0;
        try {
            ExpMonth = Integer.parseInt(txtExpMonth.getText());
            if (ExpMonth < 1 || ExpMonth > 12) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Expiration Month. Please enter a valid integer between 1 and 12.");
            return; // Stop further processing if Expiration Month is invalid
        }

        // Validate Expiration Year
        int ExpYear = 0;
        try {
            ExpYear = Integer.parseInt(txtExpYear.getText());
            if (ExpYear < 1000 || ExpYear > 9999) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Expiration Year. Please enter a valid 4-digit integer.");
            return; // Stop further processing if Expiration Year is invalid
        }

        // Validate CVV
        int CvvNumber = 0;
        try {
            CvvNumber = Integer.parseInt(Cvv, 10); // Explicitly specify base 10

            if (CvvNumber <= 0 || String.valueOf(CvvNumber).length() != 3) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid CVV. Please enter a valid 3-digit positive integer.");
            return; // Stop further processing if CVV is invalid
        }

        PaymentCard checkCard = new PaymentCard(CardName, CardNumberText, ExpMonth, ExpYear, Cvv, StreetAdd, City, State, Zip);
        Boolean checkCardResult = paymentCardDirectory.isCardInDirectory(checkCard);

        if (!checkCardResult) {
            JOptionPane.showMessageDialog(this, "Invalid Card Details");
            return;
        }
        btnPayment.setEnabled(true);
        this.paymentCard = checkCard;
        JOptionPane.showMessageDialog(this, "Please click on Make a Payment to complete your payment");
    }//GEN-LAST:event_btnCheckCardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckCard;
    private javax.swing.JButton btnCreateAcc1;
    private javax.swing.JButton btnPayment;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblCardName;
    private javax.swing.JLabel lblCardName1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblExpMonth;
    private javax.swing.JLabel lblExpYear;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAdd;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCardName;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpMonth;
    private javax.swing.JTextField txtExpYear;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAdd;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
