/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Main.LoginScreen;
import Main.TheBostonInsuranceModel;
import Model.Account.Account;
import Model.Customer.Customer;
import Model.Customer.Policy.CustomerPolicy;
import Model.Customer.Policy.CustomerPolicyDirectory;
import Model.Customer.Quote.CustomerQuote;
import Model.Customer.Quote.CustomerQuoteDirectory;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dharun Karthick Ramaraj
 */
public class CustomerMainScreen extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMainScreen
     */
    TheBostonInsuranceModel BIM;
    JPanel workPanel;
    Account account;
    CustomerQuoteDirectory customerQuoteDirectory;
    CustomerPolicyDirectory customerPolicyDirectory;
    private Customer cust;

    public CustomerMainScreen(TheBostonInsuranceModel BIM, JPanel workPanel, Account account) {
        initComponents();
        this.BIM = BIM;
        this.workPanel = workPanel;
        this.account = account;
        customerQuoteDirectory = BIM.getCustomerQuoteDirectory();
        customerPolicyDirectory = BIM.getCustomerPolicyDirectory();
                
        cust = (Customer) account;

        txtUserName.setText(String.valueOf(cust.getCustomerId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRenewReq = new javax.swing.JButton();
        btnCreateNewQuote = new javax.swing.JButton();
        btnPolicyStatus = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/topLogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("                                                              Customer Portal");

        btnRenewReq.setBackground(new java.awt.Color(204, 204, 204));
        btnRenewReq.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRenewReq.setForeground(new java.awt.Color(153, 0, 51));
        btnRenewReq.setText("Renewal Request");
        btnRenewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenewReqActionPerformed(evt);
            }
        });

        btnCreateNewQuote.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateNewQuote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateNewQuote.setForeground(new java.awt.Color(153, 0, 51));
        btnCreateNewQuote.setText("Create a quote");
        btnCreateNewQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewQuoteActionPerformed(evt);
            }
        });

        btnPolicyStatus.setBackground(new java.awt.Color(204, 204, 204));
        btnPolicyStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPolicyStatus.setForeground(new java.awt.Color(153, 0, 51));
        btnPolicyStatus.setText("Transaction Status");
        btnPolicyStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicyStatusActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setForeground(new java.awt.Color(153, 0, 0));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtUserName.setEditable(false);
        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(407, 407, 407)
                        .addComponent(btnLogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRenewReq, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateNewQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPolicyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCreateNewQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRenewReq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnPolicyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Container container = (Container) workPanel;

        container.removeAll();

        LoginScreen loginScreen = new LoginScreen(BIM, workPanel);
        workPanel.add("LoginScreen", loginScreen);

        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPolicyStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicyStatusActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workPanel.getLayout();
        TransactionStatus transactionStatus = new TransactionStatus(BIM, workPanel, account);
        workPanel.add("TransactionStatus", transactionStatus);
        layout.next(workPanel);
    }//GEN-LAST:event_btnPolicyStatusActionPerformed

    private void btnCreateNewQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewQuoteActionPerformed
        // TODO add your handling code here:
        if (customerQuoteDirectory.customerExists(cust.getCustomerId())) {
            int response = JOptionPane.showConfirmDialog(this, "An existing quote for this customer already exists. Do you want to continue with the existing quote?", "Existing Quote", JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
                CustomerQuote custQuote = customerQuoteDirectory.getCustomerQuote(cust.getCustomerId());

                // Pass the existing customer quote to the AboutYouPage
                CardLayout layout = (CardLayout) workPanel.getLayout();
                AboutYouPage aboutYouPage = new AboutYouPage(BIM, workPanel, account, custQuote);
                workPanel.add("AboutYouPage", aboutYouPage);
                layout.next(workPanel);
            } else {
                // If the user doesn't want to continue
            }
        } else {
            // If no existing quote is found, create a new customer quote
            CustomerQuote newCustQuote = new CustomerQuote(cust, "pending", 0);

            CardLayout layout = (CardLayout) workPanel.getLayout();
            AboutYouPage aboutYouPage = new AboutYouPage(BIM, workPanel, account, newCustQuote);
            workPanel.add("AboutYouPage", aboutYouPage);
            layout.next(workPanel);
        }
    }//GEN-LAST:event_btnCreateNewQuoteActionPerformed

    private void btnRenewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenewReqActionPerformed
        // TODO add your handling code here:
        if (customerPolicyDirectory.customerExists(cust.getCustomerId())) {
            // If a policy exists, proceed with the renewal request
            int response = JOptionPane.showConfirmDialog(this, "Do you want to submit a renewal request for your policy?", "Renewal Request", JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
                // Retrieve the existing customer policy
                CustomerPolicy custPolicy = customerPolicyDirectory.findCustomerPolicy(cust);

                CardLayout layout = (CardLayout) workPanel.getLayout();
                // Assuming you have a RenewPolicy class, you can replace it with your actual class
                RenewPolicy renewPolicy = new RenewPolicy(BIM, workPanel, custPolicy);
                workPanel.add("RenewPolicy", renewPolicy);
                layout.next(workPanel);
            }
        } else {
            JOptionPane.showMessageDialog(this, "You don't have an existing policy to renew.");
        }
    }//GEN-LAST:event_btnRenewReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewQuote;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPolicyStatus;
    private javax.swing.JButton btnRenewReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
