/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Main.TheBostonInsuranceModel;
import Model.Account.Account;
import Model.Customer.Customer;
import Model.Customer.Policy.CustomerPolicy;
import Model.Customer.Policy.CustomerPolicyDirectory;
import Model.Customer.Quote.CustomerQuote;
import Model.Customer.Quote.CustomerQuoteDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prane
 */
public class TransactionStatus extends javax.swing.JPanel {

    /**
     * Creates new form TransactionStatus
     */
    TheBostonInsuranceModel BIM;
    JPanel workPanel;
    Account account;
    Customer cust;
    CustomerQuoteDirectory customerQuoteDirectory;
    CustomerPolicyDirectory customerPolicyDirectory;

    public TransactionStatus(TheBostonInsuranceModel BIM, JPanel workPanel, Account account) {
        initComponents();
        this.BIM = BIM;
        this.workPanel = workPanel;
        this.account = account;
        customerQuoteDirectory = BIM.getCustomerQuoteDirectory();
        customerPolicyDirectory = BIM.getCustomerPolicyDirectory();

        cust = (Customer) account;
        txtCustID.setText(String.valueOf(cust.getCustomerId()));

        populatePolicyList();
        populateQuoteList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustPolicyList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        lblCustID = new javax.swing.JLabel();
        txtCustID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnContinueQuote = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustQuoteList1 = new javax.swing.JTable();
        btnworksheet = new javax.swing.JButton();

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/topLogo.png"))); // NOI18N

        tblCustPolicyList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Policy Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCustPolicyList);

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setForeground(new java.awt.Color(153, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 51, 153));
        jLabel.setText("                                                               Quote Status");

        lblCustID.setText("Customer ID");

        txtCustID.setEditable(false);
        txtCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setText("Click continue for the quotes with Pending status");

        btnContinueQuote.setBackground(new java.awt.Color(204, 204, 204));
        btnContinueQuote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContinueQuote.setForeground(new java.awt.Color(153, 0, 0));
        btnContinueQuote.setText("Continue the Quote");
        btnContinueQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueQuoteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("                                                               Policy Status");

        tblCustQuoteList1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Quote Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCustQuoteList1);

        btnworksheet.setBackground(new java.awt.Color(204, 204, 204));
        btnworksheet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnworksheet.setForeground(new java.awt.Color(153, 0, 0));
        btnworksheet.setText("view worksheet");
        btnworksheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnworksheetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(370, 370, 370)
                        .addComponent(lblCustID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(150, 150, 150)
                            .addComponent(btnContinueQuote))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnworksheet)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)))))
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblCustID)
                    .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnworksheet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinueQuote))
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(505, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workPanel.remove(this);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.previous(workPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustIDActionPerformed

    private void btnContinueQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueQuoteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustQuoteList1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Quote");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustQuoteList1.getModel();
        CustomerQuote custQuote = (CustomerQuote) model.getValueAt(selectedRow, 0);

        if (custQuote.getQuote().getStatus().equalsIgnoreCase("Unauthorized")) {
            JOptionPane.showMessageDialog(this, "This quote is unauthorized. It must be approved by an underwriter before you can continue.");
            return;
        }

        CardLayout layout = (CardLayout) workPanel.getLayout();
        UI.Customer.AboutYouPage aboutYouPage = new UI.Customer.AboutYouPage(BIM, workPanel, account, custQuote);
        workPanel.add("AboutYouPage", aboutYouPage);
        layout.next(workPanel);
    }//GEN-LAST:event_btnContinueQuoteActionPerformed

    private void btnworksheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnworksheetActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustPolicyList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a policy from the above table to view details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustPolicyList.getModel();
        CustomerPolicy custPolicy = (CustomerPolicy) model.getValueAt(selectedRow, 0);
        PolicyWorksheet policyWorksheetPage = new PolicyWorksheet(BIM, workPanel, custPolicy);
        workPanel.add(policyWorksheetPage, "PolicyWorksheetPage");
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "PolicyWorksheetPage");
    }//GEN-LAST:event_btnworksheetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContinueQuote;
    private javax.swing.JButton btnworksheet;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCustID;
    private javax.swing.JTable tblCustPolicyList;
    private javax.swing.JTable tblCustQuoteList1;
    private javax.swing.JTextField txtCustID;
    // End of variables declaration//GEN-END:variables

    private void populatePolicyList() {
        DefaultTableModel model = (DefaultTableModel) tblCustPolicyList.getModel();
        model.setRowCount(0);

        CustomerPolicy customerPolicy = customerPolicyDirectory.findCustomerPolicy(cust);

        if (customerPolicy != null) {
            Object[] row = {customerPolicy, customerPolicy.getPolicy().getStatus()};
            model.addRow(row);
        }
    }

    private void populateQuoteList() {
        DefaultTableModel model = (DefaultTableModel) tblCustQuoteList1.getModel();
        model.setRowCount(0); // Clear existing rows

        // Get the customer's quote from the customerQuoteDirectory
        CustomerQuote customerQuote = customerQuoteDirectory.findCustomerQuote(cust);

        if (customerQuote != null) {
            // Populate the table with the quote's details
            Object[] row = {customerQuote, customerQuote.getQuote().getStatus()};
            model.addRow(row);
        }
    }

}
