/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Model.Account.Account;
import Model.Account.AccountCredentials;
import Model.Account.AccountCredentialsDirectory;
import UI.Comp.Admin.AdminMainScreen;
import UI.Comp.Agent.AgentMainScreen;
import UI.Comp.Underwriter.UnderwriterMainScreen;
import UI.Customer.CustomerMainScreen;
import UI.Thirdparty.PAYMENT.VerifySyncBillingLogin;
import UI.Thirdparty.POLK.POLKLoginScreen;
import UI.Thirdparty.VIN.VINAuditLoginScreen;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dharun Karthick Ramaraj
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    TheBostonInsuranceModel BIM;
    JPanel workPanel;

    public LoginScreen(TheBostonInsuranceModel BIM, JPanel workPanel) {
        initComponents();
        this.BIM = BIM;
        this.workPanel = workPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnBillingCompany = new javax.swing.JButton();
        btnVINDataCompany = new javax.swing.JButton();
        btnVINVerifyCompany = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/LoginScreen.png"))); // NOI18N

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 51, 153));
        jLabel.setText("            User Login ");

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(153, 0, 51));
        lblUserName.setText("User Name: ");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 0, 51));
        lblPassword.setText("Password: ");

        btnLogin.setBackground(new java.awt.Color(0, 102, 153));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnBillingCompany.setBackground(new java.awt.Color(0, 204, 204));
        btnBillingCompany.setText("VerifySyncBilling");
        btnBillingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingCompanyActionPerformed(evt);
            }
        });

        btnVINDataCompany.setBackground(new java.awt.Color(0, 204, 204));
        btnVINDataCompany.setText("POLK");
        btnVINDataCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVINDataCompanyActionPerformed(evt);
            }
        });

        btnVINVerifyCompany.setBackground(new java.awt.Color(0, 204, 204));
        btnVINVerifyCompany.setText("VINAudit");
        btnVINVerifyCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVINVerifyCompanyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Quick Access with Third-Party Logins");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBillingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVINDataCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnVINVerifyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVINVerifyCompany)
                    .addComponent(btnVINDataCompany)
                    .addComponent(btnBillingCompany))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String userID = txtUserName.getText();
        String password = txtPassword.getText();

        AccountCredentialsDirectory credentialsDirectory = BIM.getAccountCredentialsDirectory();
        AccountCredentials authenticatedCredentials = credentialsDirectory.authenticateUser(userID, password);

        if (authenticatedCredentials != null) {
            // Authentication successful
            txtUserName.setText("");
            txtPassword.setText("");
            String role = authenticatedCredentials.getRole();
            Account account = authenticatedCredentials.getAccount();
            CardLayout layout = (CardLayout) workPanel.getLayout();

            switch (role.toLowerCase()) {
                case "admin":
                    AdminMainScreen adminMainScreen = new AdminMainScreen(BIM, workPanel, account);
                    workPanel.add("AdminMainScreen", adminMainScreen);
                    layout.next(workPanel);
                    break;
                case "agent":
                    AgentMainScreen agentMainScreen = new AgentMainScreen(BIM, workPanel, account);
                    workPanel.add("AgentMainScreen", agentMainScreen);
                    layout.next(workPanel);
                    break;
                case "underwriter":
                    UnderwriterMainScreen underwriterMainScreen = new UnderwriterMainScreen(BIM, workPanel, account);
                    workPanel.add("UnderwriterMainScreen", underwriterMainScreen);
                    layout.next(workPanel);
                    break;
                case "customer":
                    CustomerMainScreen customerMainScreen = new CustomerMainScreen(BIM, workPanel, account);
                    workPanel.add("CustomerMainScreen", customerMainScreen);
                    layout.next(workPanel);
                    break;
                default:
                    // Handle unknown role
                    break;
            }
        } else {
            // Authentication failed
            JOptionPane.showMessageDialog(this, "Invalid Credentials");
            txtPassword.setText("");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnVINDataCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVINDataCompanyActionPerformed
        // TODO add your handling code here:
        POLKLoginScreen polkLoginScreen = new POLKLoginScreen(BIM, workPanel);
        workPanel.add("POLKLoginScreen", polkLoginScreen);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }//GEN-LAST:event_btnVINDataCompanyActionPerformed

    private void btnVINVerifyCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVINVerifyCompanyActionPerformed
        // TODO add your handling code here:
        VINAuditLoginScreen vinAuditLoginScreen = new VINAuditLoginScreen(BIM, workPanel);
        workPanel.add("VINAuditLoginScreen", vinAuditLoginScreen);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }//GEN-LAST:event_btnVINVerifyCompanyActionPerformed

    private void btnBillingCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingCompanyActionPerformed
        // TODO add your handling code here:
        VerifySyncBillingLogin verifySyncBillingLogin = new VerifySyncBillingLogin(BIM, workPanel);
        workPanel.add("VerifySyncBillingLogin", verifySyncBillingLogin);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }//GEN-LAST:event_btnBillingCompanyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillingCompany;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnVINDataCompany;
    private javax.swing.JButton btnVINVerifyCompany;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
