/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Comp.Agent;

import Main.LoginScreen;
import Main.TheBostonInsuranceModel;
import Model.Account.Account;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author Dharun Karthick Ramaraj
 */
public class AgentMainScreen extends javax.swing.JPanel {

    /**
     * Creates new form AgentMainScreen
     */
    private TheBostonInsuranceModel BIM;
    private JPanel workPanel;
    private Account account;
    public AgentMainScreen(TheBostonInsuranceModel BIM,JPanel workPanel,Account account) {
        initComponents();
        this.BIM = BIM;
        this.workPanel = workPanel;
        this.account = account;
        
        txtUserName.setText(account.getAccountCredentials().getUserID());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCreateAcc = new javax.swing.JButton();
        btnCreateQuote = new javax.swing.JButton();
        btnViewCustomers = new javax.swing.JButton();
        btnViewQuotePendingStatus = new javax.swing.JButton();
        btnRenewPolicy = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(665, 492));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/topLogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("                                                         Agent Portal");

        jLabel2.setText("Manage Customer");

        jLabel3.setText("Manage Policies and Quotes");

        btnCreateAcc.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateAcc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(153, 0, 51));
        btnCreateAcc.setText("Create a Account");
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });

        btnCreateQuote.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateQuote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateQuote.setForeground(new java.awt.Color(153, 0, 51));
        btnCreateQuote.setText("Create a Quote");
        btnCreateQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateQuoteActionPerformed(evt);
            }
        });

        btnViewCustomers.setBackground(new java.awt.Color(204, 204, 204));
        btnViewCustomers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewCustomers.setForeground(new java.awt.Color(153, 0, 51));
        btnViewCustomers.setText("View all Customers");
        btnViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomersActionPerformed(evt);
            }
        });

        btnViewQuotePendingStatus.setBackground(new java.awt.Color(204, 204, 204));
        btnViewQuotePendingStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewQuotePendingStatus.setForeground(new java.awt.Color(153, 0, 51));
        btnViewQuotePendingStatus.setText("View Quotes with Pending Status");
        btnViewQuotePendingStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewQuotePendingStatusActionPerformed(evt);
            }
        });

        btnRenewPolicy.setBackground(new java.awt.Color(204, 204, 204));
        btnRenewPolicy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRenewPolicy.setForeground(new java.awt.Color(153, 0, 51));
        btnRenewPolicy.setText("Renew Issued Policies");
        btnRenewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenewPolicyActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setForeground(new java.awt.Color(153, 0, 0));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtUserName.setEditable(false);
        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(407, 407, 407)
                        .addComponent(btnLogout))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnCreateQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnViewCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnViewQuotePendingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(100, 100, 100)
                            .addComponent(btnRenewPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewQuotePendingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenewPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workPanel.getLayout();
        CreateCustAccount createCustAccount = new CreateCustAccount(BIM,workPanel);
        workPanel.add("CreateCustAccount",createCustAccount);      
        layout.next(workPanel);
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnCreateQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateQuoteActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workPanel.getLayout();
        CreateCustQuote createCustQuote = new CreateCustQuote(BIM,workPanel,account);
        workPanel.add("CreateCustQuote",createCustQuote);      
        layout.next(workPanel);
    }//GEN-LAST:event_btnCreateQuoteActionPerformed

    private void btnViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomersActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workPanel.getLayout();
        ViewCustAccounts viewCustAccounts = new ViewCustAccounts(BIM,workPanel);
        workPanel.add("ViewCustAccounts",viewCustAccounts);      
        layout.next(workPanel);
    }//GEN-LAST:event_btnViewCustomersActionPerformed

    private void btnRenewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenewPolicyActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workPanel.getLayout();
        RenewPolicy viewPolicies = new RenewPolicy(BIM,workPanel);
        workPanel.add("ViewPolicies",viewPolicies);      
        layout.next(workPanel);
    }//GEN-LAST:event_btnRenewPolicyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Container container = (Container) workPanel;

        container.removeAll();

        LoginScreen loginScreen = new LoginScreen(BIM, workPanel);
        workPanel.add("loginScreen", loginScreen);

        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewQuotePendingStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewQuotePendingStatusActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) workPanel.getLayout();
        ViewQuotes viewQuotes = new ViewQuotes(BIM,workPanel,account);
        workPanel.add("ViewQuotes",viewQuotes);
        layout.next(workPanel);
    }//GEN-LAST:event_btnViewQuotePendingStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnCreateQuote;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRenewPolicy;
    private javax.swing.JButton btnViewCustomers;
    private javax.swing.JButton btnViewQuotePendingStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
